spring:
  application:
    name: ai-junior-developer
  web:
    resources:
      add-mappings: true

service:
  workspace:
    path: C://Projects/ai-junior-developer-workspace
  jira:
    webhook-secret: change-me
    username: eugen.public@gmail.com
    base-url: https://eugenscobich.atlassian.net/
    api-token: change-me

