spring:
  application:
    name: ai-junior-developer
  web:
    resources:
      add-mappings: true

service:
  workspace:
    path: C://Projects//ai-junior-developer-workspace
  jira:
    webhook-secret: change-me
    username: eugen.public@gmail.com
    base-url: https://eugenscobich.atlassian.net/
    api-token: change-me
    user-id: 712020:89ee716f-8686-4974-89a2-f42027720d71
    tread-id-custom-field-name: customfield_10059
    component-custom-field-name: customfield_10058
    open-ai-model-custom-field-name: customfield_10091
  github:
    api-token: change-me
    webhook-secret: change-me
    user-id: 210500703
  toggle-ai:
    assistant: false

logging:
  pattern:
    correlation: "[%X{assistantId},%X{threadId:-},%X{runId:-}] "